### ISSUE TITLE
Stream output of `wl-mirror` over the network

### ISSUE THREAD

**Issue by savchenko** [Ferdi265/wl-mirror#1]
Thinking of possible use-cases, have you tried (was thinking of) using its output to further stream via `ffmpeg`, etc?

**Comment by Ferdi265** [comment]
That is not one of the intended use cases of this program.

A better program to use for this is OBS with the [wlrobs][1] extension. In fact, the dmabuf streaming code used in this project comes directly from wlrobs and OBS.

[1]: https://hg.sr.ht/~scoopta/wlrobs
