### ISSUE TITLE
Support opening an xwayland shell

### ISSUE THREAD

**Issue by zeroeightysix** [Ferdi265/wl-mirror#15]
Okay, forgive me for the cursed suggestion.

Until recently I've been using a [gnome casting test script](https://gitlab.gnome.org/-/snippets/19) to be able to share my screen in X11-only applications, such as (non-ozone) Chrome and Discord. The test script would spawn an X11 window with a capture of my screen on it, which Discord is then able to screenshare.

Unfortunately, the script has stopped working. Instead of trying to fix it, a better performing (and non-green?) solution such as wl-mirror would be preferable - if it was able to show X11 windows.

**Comment by Ferdi265** [comment]
Hi!

I actually don't find that to be so cursed at all. I have actually thought about something like this as well.

The codebase for `wl-mirror` is very Wayland-specific and adding an X11 windowing backend to it and getting OpenGL going would require quite a lot of new boilerplate, to the point where it might make sense to have a redesigned project that is intended to decouple the display part and maybe uses a toolkit to reduce boilerplate. At that point adding support for the dbus / xdg-desktop-portal / pipewire method for capturing the screen might also make sense, to support more desktops.

The idea is a good one though. Programs that can record X11 desktops and windows but not Wayland desktops and windows are common, and having a bridge for that would be great. It is a bit of a bigger project though, so I think it's gonna take a while.

I will leave this issue open until I decide what exactly I'm gonna do about that. Something like that definitely should exist.

**Comment by Ferdi265** [comment]
Since this will probably take a while to implement in wl-mirror, here is a link that might interest you:

The KDE People have built a transparent Wayland to X11 screenshare shim, the [XWayland Video Bridge](https://invent.kde.org/davidedmundson/xwaylandvideobridge). It might just fix your problem with screensharing :)

**Comment by zeroeightysix** [comment]
> The KDE People have built a transparent Wayland to X11 screenshare shim, the [XWayland Video Bridge](https://invent.kde.org/davidedmundson/xwaylandvideobridge). It might just fix your problem with screensharing :)

Wow! Thanks for the link. This project looks great!

**Comment by Ferdi265** [comment]
closing this in favor of XWayland Video Bridge, and also because wl-mirror is so wayland-centric that this will likely never be otherwise implemented
