### ISSUE TITLE
Options for --panscan=1 --no-keepaspect-window

### ISSUE THREAD

**Issue by digitalsignalperson** [Ferdi265/wl-mirror#20]
It would be fun to implement something similar to what you can do with `mpv --panscan=1 --no-keepaspect-window`, where the window is not locked to the original aspect ratio, and it will crop the tops or the sides for best fit. This is like getting rid of black bars on the sides. I recommend playing a video with mpv and these options and resizing the window in different shapes to understand what it does.

I think this is already scriptable with --region, but it could be handy as a built in option.

from https://mpv.io/manual/master/#options-panscan
> --panscan=<0.0-1.0>
> Enables pan-and-scan functionality (cropping the sides of e.g. a 16:9 video to make it fit a 4:3 display without black bands). The range controls how much of the image is cropped. May not work with all video output drivers.
> 
> This option has no effect if --video-unscaled option is used.

and can see how it calculates the aspect with panscan here https://github.com/mpv-player/mpv/blob/master/video/out/aspect.c#L29

**Comment by Ferdi265** [comment]
Hi! Thanks for the suggestion! I'm investigating implementing this as a `--crop` option. I don't have a lot of free time until the start of October, but look forward to this feature potentially landing sometime mid-october.

**Comment by Ferdi265** [comment]
Hi! I have worked a bit on the scaling options and have implemented a `--scaling cover` option in the [next](https://github.com/Ferdi265/wl-mirror/tree/next) branch that will crop the mirrored image on the sides or top and bottom depending on which would result in a larger image.

The new scaling options apply independently of the scaling filters so if you want to use nearest neighbor scaling you can use `--scaling cover --scaling nearest`.

If this implementation is to your liking I will merge this into `main` and release this as 0.16.0.

**Comment by Ferdi265** [comment]
released in 0.16.0. If you have any more comments regarding this, or the behaviour is not to your liking, feel free to comment and I'll reopen the issue.
