### ISSUE TITLE
Ability to mirror one specific desktop of sway

### ISSUE THREAD

**Issue by chgardener** [Ferdi265/wl-mirror#21]
Hey there! 

First if all, wl-mirror works like a charm. I love it. 

It would be awesome if I could also specify one of the desktops of sway to be mirrored, for example I'd like to choose desktop one to be mirrored. 

That would be really useful when presenting. That way one app can be shown to the audience while I can do something else on the computer without that being visible.

Thanks a lot!

**Comment by Ferdi265** [comment]
Marking this as both "wontfix" and "upstream-bug" since I consider it a bug that sway does not allow at least window screensharing from xdg-portal. However, the full featureset hoped for in this issue will probably never be supported on sway as it stands.
