### ISSUE TITLE
Sway crashes if external monitor is unplugged

### ISSUE THREAD

**Issue by jalvesaq** [Ferdi265/wl-mirror#25]
Sway crashes if wl-mirror is mirroring the output of an external monitor connected to the HDMI port and the monitor is unplugged.

Steps to reproduce:

1. Plug an external monitor into the HDMI port.
2. Run: `wl-mirror HDMI-A-1 &`
3. Unplug the external monitor.

Expected behavior: wl-mirror quits gracefully when the monitor of the mirrored output is unplugged.

I use wl-mirror in my classes, but instead of mirroring the output of my laptop display and moving wl-mirror window to the output of the projector, I prefer to do the inverse to be able to open different applications in workspaces of my laptop's output and only send to the projector's workspace what I want the audience to see. Then, I switch to the workspace where wl-mirror is running fullscreen and finally to the external monitor's workspace. It's a perfect setup! Thank you very much for wl-mirror! I have only to remember of closing wl-mirror before unplugging the HDMI cable.

**Comment by Ferdi265** [comment]
Hi! If sway crashes when a monitor that is being mirrored disappears, then that is likely a sway bug, not wl-mirror. wl-mirror handles disappearing of monitors gracefully, and I remember testing things like that when I originally wrote it.

I currently do not have an external monitor near me to test with, but I will try to reproduce your issue anyway and investigate (and regardless of who's at fault, I'll try to find a fix).

In the meantime, please check your sway and wl-mirror version and please report the bug in the sway issue tracker.

**Comment by jalvesaq** [comment]
I'm using Sway 1.8.1 on Debian testing, and I compiled wl-mirror from the source. I will report the bug in sway too. Thanks!

**Comment by jalvesaq** [comment]
I uninstalled Nvidia drivers, and there is no crash with Nouveau. Since Nvidia is an unsupported  GPU, I'm closing the issue. I'm sorry for wasting your time.
