### ISSUE TITLE
Black output when mirroring monitor connected to secondary (nouveau) GPU

### ISSUE THREAD

**Issue by sochotnicky** [Ferdi265/wl-mirror#5]
I have 2 GPUS, each has one monitor connected. I can easily mirror the monitor connected to my intel (main) GPU, but trying to mirror monitor connected to secondary GPU (nouveau) only results in black "screen".

OBS/pipewire has no problem sharing the secondary screen so I assume it's possible at least in some way. I can provide more detailed info if needed.

I also personally don't need this to work (since I'd use this on a laptop with just one GPU) but I thought I'd still file this in case you'd want to investigate/fix

**Comment by Ferdi265** [comment]
Thanks! that sounds interesting!

On first glance, it looks like maybe wlr-export-dmabuf only works "within" the same GPU (I wonder if it works if you start wl-mirror with the same GPU as the output that is black now).
I currently only have an intel-only setup, so I didn't notice this at first.

As for why it works in OBS: There's currently three ways to record wayland in OBS.

- the desktop portal / pipewire plugin: OBS asks `xdg-desktop-portal-wlr` to start recording the screen and streams it over pipewire
- the wlrobs plugin with the dmabuf source (this is the exact wayland protocol wl-mirror uses, in fact, most of the mirroring code in this project is from there)
- the wlrobs plugin with the screencopy source

I think most helpful would be to see if it's only the screencopy source that works on OBS, or if dmabuf works as well in wlrobs, and I just messed something up in wl-mirror.

If neither of the two wlrobs sources work, then I might have to look into what xdg-desktop-portal-wlr does.

**Comment by sochotnicky** [comment]
starting wl-mirror on the same monitor/gpu as is being mirrored does not help. Actually if I understand how things are done - the rendering is all done in my primary GPU and the secondary is just used to drive the output and put bits into it...

On to OBS comparison:
 * Pipewire works and has been pretty stable in my case for a while (either of the monitors can be shared as needed)
 * wlrobs plugin using dmabuf now crashes obs (I have a vague memory it worked but I haven't used it in a long time so not sure if this is expected). I tried latest hg tip of wlrobs + obs 27.1.3, maybe some other combination would work better for testing things out
 * wlrobs + screencopy source works on both monitors (but that's not very helpful I suppose)

**Comment by Ferdi265** [comment]
Thanks! That actually helps a lot.

I wanted to make a screencopy backend for wl-mirror at some point anyway, so I think I will go that route.

About the OBS crash: that's interesting. does it always crash using the dmabuf source or only when recording the output connected to the other GPU?

**Comment by sochotnicky** [comment]
It's a wlrobs/dmabuf thing - I haven't bothered to investigate since as far as I am concerned it's superseded by pipewire recording which is built-in

**Comment by sochotnicky** [comment]
Not sure this will help but when I run wl-mirror --verbose I get repeated messages like this:
```
debug: frame_callback: requesting next callback
debug: frame_callback: rendering frame
debug: frame_callback: swapping buffers
debug: frame_callback: clearing dmabuf_frame state
debug: frame_callback: creating wlr_dmabuf_export_frame
debug: frame_callback: adding dmabuf_frame event listener
debug: dmabuf_frame: frame was canceled
debug: dmabuf_frame: temporary cancellation
debug: dmabuf_frame: closing files
```

The "frame was cancelled" part looks suspicious of course

**Comment by Ferdi265** [comment]
Hi!

I have implemented support for the wlr-screencopy protocol in the [backends](/Ferdi265/wl-mirror/tree/backends) branch.

It's still a little experimental, but it might fix wl-mirror for you.

wl-mirror will automatically fall back to the new backend if the dmabuf backend fails 10 times in a row, but you can also select it manually with `--backend screencopy`.

**Comment by Ferdi265** [comment]
Once this is cleaned up and tested properly, I will release this as 0.9.0.

**Comment by Ferdi265** [comment]
0.9.0 has been released.

I have not been able to reproduce your bug yet, and therefore can't say for sure that this fixes it, but it's very likely.
I will leave this issue open until I have confirmation that the bug is fixed.

**Comment by sochotnicky** [comment]
I am away from my usual computer for a while so can't retest, but I have added a TODO for myself and as soon as I am back (~1 week) I will let you know.

**Comment by sochotnicky** [comment]
So I have retested and wl-mirror 0.9.2 works on nouveau GPU output mirroring as well. However... it also works when I force dmabuf backend. So it's possible the actual bug was somewhere in lower layer (nouveau driver/mesa/wlroots etc).

Either way this seems fixed and I think having the fallback from dmabuf is still a good idea for some corner cases. Once again - thanks for this neat utility.

**Comment by Ferdi265** [comment]
Nice to see it works for you as well now :)
