### ISSUE TITLE
Purpose of `--no-fullscreen-output`

### ISSUE THREAD

**Issue by danielrainer** [Ferdi265/wl-mirror#52]
Reading the documentation of `wl-mirror` I got confused by the `--no-fullscreen-output` option. The documentation explains it as `open wl-mirror as fullscreen on the current output (default)`, which is surprising, since the `no-fullscreen` part made me expect that it will not launch fullscreened (which it doesn't when this option is provided). It also seems at odds with the description of `--no-fullscreen`: `open wl-mirror as a window (default)`.

**Comment by Ferdi265** [comment]
Hi!

The documentation for this option is a bit suboptimal:

Normally, wl-mirror opens as a window. `--fullscreen` and `--no-fullscreen` change whether the wl-mirror window is fullscreen or not.

Normally, when fullscreening wl-mirror, it fullscreens on the output the window is currently on. `--fullscreen-output <OUTPUT>` and `--no-fullscreen-output` change the target output on which wl-mirror will be fullscreened.

In hindsight `--fullscreen-target-output` would have been a better name, but that is quite long. I will update the documentation to clarify this.

**Comment by Ferdi265** [comment]
Do you think "--fullscreen-output O ... Set fullscreen target output to output O" and "--no-fullscreen-output ... Unset fullscreen target output" would be clear enough for `--help` text?

**Comment by danielrainer** [comment]
Ah, that makes sense, thanks for explaining. Maybe use somewhat more verbose descriptions to explain the options, like

```text
--fullscreen-output O      display wl-mirror on output O when fullscreened by --fullscreen (implies --fullscreen)
--no-fullscreen-output     display wl-mirror on the current output when fullscreened (default). does not affect whether the window is fullscreened or not
```

I think also for the other fullscreen options using `open` instead of `display` or something similar is suboptimal, since these options can be used in stream mode, when wl-mirror is already open.

Part of the confusion in my testing of the option was caused by different behavior between specifying `--fullscreen` (or `--fullscreen-output`) in stream mode, which works as you describe, and using the window manager shortcut I usually use for fullscreening, which always fullscreens the window on the current output, regardless of what was specified by `--fullscreen-output`. But I think I actually like the behavior the way it is now, meaning fullscreening via the window manager works as it does with other applications, and fullscreening via `--fullscreen` respects `--fullscreen-output`.

**Comment by Ferdi265** [comment]
Thanks for the input!

I think `--fullscreen-output` implying `--fullscreen`, but `--no-fullscreen-output` not implying `--no-fullscreen` is potentially confusing, so I'm considering changing this, since otherwise the behaviour is otherwise weirdly asymmetric.

**Comment by Ferdi265** [comment]
I went with similar text as my suggestion, but tried to incorporate your feedback:

- don't use the term "open" when the option also applies in stream mode
- explicitly note which other options are implied

I also split the documentation for fullscreening and unfullscreening into two paragraphs in the man page since I thought this made the explanation clearerer.

I hope this helps!
