### ISSUE TITLE
Full screen mirroring on multiple displays

### ISSUE THREAD

**Issue by AA-san-AA** [Ferdi265/wl-mirror#55]
I have three display devices A, B, and C, and I want B and C to use wl-mirror to replicate A. 
Currently, I can only manually execute wl-mirror twice and specify the output devices. such as: wl-mirror B A and wl-mirror C A.
Is there a more convenient way to do this?

**Comment by Ferdi265** [comment]
Hi! Currently there is no way for a single instance of wl-mirror to mirror into multiple destination windows, so as you already said, you have to run two instances of wl-mirror.

You can use `wl-mirror output-A --fullscreen-output output-B` to automatically fullscreen the window on the correct output, and if you want multiple instances, you could create a short script that launches wl-mirror twice on two outputs automatically or just start it twice.
