### ISSUE TITLE
--fullscreen doesn't work since 0.17.0

### ISSUE THREAD

**Issue by zboszor** [Ferdi265/wl-mirror#57]
With wl-mirror 0.17.0, with both `cmake -DWITH_LIBDECOR=ON/OFF`, `wl-mirror` is windowed even with `--fullscreen` and there is decoration and a title in the window. How can I disable it? Or should I just go back to 0.16.5?

**Comment by Ferdi265** [comment]
this sounds like a bug, but I'm not sure what causes this.

What compositor are you using? I can't teproduce this on sway 1.10, neither with nor without libdecor.

**Comment by zboszor** [comment]
I have seen this with both wlroots 0.18.1 + sway 1.10 and current master from both, i.e. https://github.com/swaywm/sway/commit/62fd8c4d011ea4dc360831723a3844c0e4439f32 and https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/c0945b661369dd11d5e80a6cee038146dd6098ce

**Comment by zboszor** [comment]
FWIW, I am using https://codeberg.org/flk/meta-wayland/ under Yocto 5.1 plus backported wayland-protocols 1.38 from Yocto master in order to be able to test the very latest wlroots/sway versions and in a few weeks, Mesa 24.3.x.

**Comment by zboszor** [comment]
The current build I have does not use libdecor:
```
[root@dtd ~]# ldd /usr/bin/wl-mirror 
	linux-vdso.so.1 (0x00007f95351ba000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f95350af000)
	libwayland-egl.so.1 => /usr/lib/libwayland-egl.so.1 (0x00007f95350aa000)
	libEGL.so.1 => /usr/lib/libEGL.so.1 (0x00007f9535050000)
	libGLESv2.so.2 => /usr/lib/libGLESv2.so.2 (0x00007f9535044000)
	libwayland-client.so.0 => /usr/lib/libwayland-client.so.0 (0x00007f9535032000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f9534e46000)
	/usr/lib/ld-linux-x86-64.so.2 (0x00007f95351bc000)
	libgallium-24.2.6.so => /usr/lib/libgallium-24.2.6.so (0x00007f9532800000)
	libgbm.so.1 => /usr/lib/libgbm.so.1 (0x00007f95327f0000)
	libglapi.so.0 => /usr/lib/libglapi.so.0 (0x00007f95327bc000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f9532791000)
	libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x00007f953278c000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f9532761000)
	libxcb-dri2.so.0 => /usr/lib/libxcb-dri2.so.0 (0x00007f9532758000)
	libxcb-randr.so.0 => /usr/lib/libxcb-randr.so.0 (0x00007f9532746000)
	libxcb-xfixes.so.0 => /usr/lib/libxcb-xfixes.so.0 (0x00007f953273d000)
	libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x00007f9532738000)
	libdrm.so.2 => /usr/lib/libdrm.so.2 (0x00007f9532721000)
	libwayland-server.so.0 => /usr/lib/libwayland-server.so.0 (0x00007f9532709000)
	libxcb-dri3.so.0 => /usr/lib/libxcb-dri3.so.0 (0x00007f9532700000)
	libxcb-present.so.0 => /usr/lib/libxcb-present.so.0 (0x00007f95326fb000)
	libxcb-sync.so.1 => /usr/lib/libxcb-sync.so.1 (0x00007f95326f2000)
	libxshmfence.so.1 => /usr/lib/libxshmfence.so.1 (0x00007f95326ed000)
	libffi.so.8 => /usr/lib/libffi.so.8 (0x00007f95326e1000)
	libLLVM.so.18.1 => /usr/lib/libLLVM.so.18.1 (0x00007f952be00000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f95326c4000)
	libzstd.so.1 => /usr/lib/libzstd.so.1 (0x00007f95325f7000)
	libdrm_radeon.so.1 => /usr/lib/libdrm_radeon.so.1 (0x00007f95325e9000)
	libelf.so.1 => /usr/lib/libelf.so.1 (0x00007f95325cd000)
	libdrm_amdgpu.so.1 => /usr/lib/libdrm_amdgpu.so.1 (0x00007f95325c1000)
	libdrm_intel.so.1 => /usr/lib/libdrm_intel.so.1 (0x00007f953259a000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f952ba00000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f952bdd2000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f9532595000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f953258d000)
	libedit.so.0 => /usr/lib/../lib/libedit.so.0 (0x00007f952bd97000)
	libxml2.so.2 => /usr/lib/../lib/libxml2.so.2 (0x00007f952b8b4000)
	libpciaccess.so.0 => /usr/lib/libpciaccess.so.0 (0x00007f953257f000)
	libncurses.so.5 => /usr/lib/libncurses.so.5 (0x00007f952bd6f000)
	libtinfo.so.5 => /usr/lib/libtinfo.so.5 (0x00007f952bd3d000)
[root@dtd ~]# ldd /usr/bin/wl-mirror | grep decor
[root@dtd ~]# 
```

**Comment by Ferdi265** [comment]
> The current build I have does not use libdecor:

For builds without libdecor, the fullscreen and decoration behaviour should be the same as with 0.16.5. No deliberate changes were made to the configure code path, but after a quick glance at the fullscreening code the logic is a bit fishy, so maybe this results in strange behaviour in some cases. If my guess is correct, then you should see the same behaviour if you downgrade wl-mirror to 0.16.5, but leave everything else (sway, wlroots, etc...) the same.

What would also help is the output of `wl-mirror` with `--verbose` and the `WAYLAND_DEBUG=1` env var set. That way I can see what actually happened when fullscreening.

**Comment by zboszor** [comment]
This is not an issue in wl-mirror.

It turns out that it's the same problem I see when trying to run two Chromium browser instances on two monitors.
The second instance bound to the secondary output must start a little later than the first instance. When they are started in the reverse order, i.e. the first instance bound to the primary output starts later, it kicks the fullscreen application on the secondary output out of fullscreen mode, and gets decoration.

See https://github.com/swaywm/sway/issues/8265

This is reproducible with wl-mirror now. It wasn't with sway 1.9, but with it occurs with sway 1.10 and git master.

**Comment by Ferdi265** [comment]
thanks. marking as upstream bug for future reference
