### ISSUE TITLE
Colour inverting mirrored surface

### ISSUE THREAD

**Issue by WhyNotHugo** [Ferdi265/wl-mirror#7]
When consuming media or watching screen casts, I often have to stare at black text on white background, which is rather painful during these dark winter days.

I'd like to use wl-mirror to mirror the original window but inverting colours -- in this case, so that I get white text on black background.

Can this maybe be implemented as a transform?

**Comment by Ferdi265** [comment]
implemented as `-i` or `--invert-colors` in v0.6.0
